trigger:
    - main
    
    pool:
      vmImage: 'ubuntu-latest'
    
    variables:
      azureServiceConnection: 'mPersona-Service-Connection'
      webAppName: 'mpersona-vue'
    
    stages:
    - stage: Build
      jobs:
      - job: BuildJob
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x' # Use the latest supported LTS version
          displayName: 'Install Node.js'
    
        - script: |
            npm install
            npm run build
          displayName: 'Install dependencies and build'
    
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
            replaceExistingArchive: true
          displayName: 'Archive files'
    
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: 'Publish Artifact'
    
    - stage: Deploy
      dependsOn: Build
      condition: succeeded()
      jobs:
      - deployment: DeploymentJob
        environment: production # Ensure this environment exists in Azure DevOps
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$(azureServiceConnection)'
                  appType: 'webAppLinux'
                  appName: '$(webAppName)'
                  package: '$(Pipeline.Workspace)/drop/$(webAppName).zip'
                  runtimeStack: 'NODE|16-lts' # Use the latest supported LTS version
                displayName: 'Deploy to Azure Web App'